<?php
/**
 * @category   Attachment
 * @package    Attachment_Files
 * @author     fr@narola.email
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Attachment\Files\Block;

use Magento\Framework\View\Element\Template\Context;
use Attachment\Files\Model\FilesFactory;
/**
 * Files List block
 */
class FilesListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Files
     */
    protected $_files;
    public function __construct(
        Context $context,
        FilesFactory $files
    ) {
        $this->_files = $files;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Attachment Files Module List Page'));
        
        if ($this->getFilesCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'attachment.files.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getFilesCollection()
            );
            $this->setChild('pager', $pager);
            $this->getFilesCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getFilesCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 5;

        $files = $this->_files->create();
        $collection = $files->getCollection();
        $collection->addFieldToFilter('status','1');
        //$files->setOrder('files_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}