<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
 <div id="complete-graph">      
    <?php if ($block->getCount()) : ?>
    <div class="dashboard-diagram-image">
        <img src="<?= $block->escapeUrl($block->getChartUrl(false)) ?>" class="dashboard-diagram-chart" alt="Chart" title="Chart" />
    </div>
    <?php else : ?>
    <div class="dashboard-diagram-nodata">
        <span><?= $block->escapeHtml(__('No Data Found')) ?></span>
    </div>
    <?php endif; ?>

</div>